"""create pipelines table

Revision ID: dfcc5689372a
Revises: cb20049b09fe
Create Date: 2026-07-16 14:36:57.599333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcc5689372a'
down_revision: Union[str, Sequence[str], None] = 'cb20049b09fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('pipeline_type', sa.String(length=30), nullable=False))
    op.add_column('pipelines', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('pipelines', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('pipelines', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('pipelines', sa.Column('updated_by', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('pipelines_name_key'), 'pipelines', type_='unique')
    op.create_index(op.f('ix_pipelines_name'), 'pipelines', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelines_name'), table_name='pipelines')
    op.create_unique_constraint(op.f('pipelines_name_key'), 'pipelines', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('pipelines', 'updated_by')
    op.drop_column('pipelines', 'created_by')
    op.drop_column('pipelines', 'is_active')
    op.drop_column('pipelines', 'version')
    op.drop_column('pipelines', 'pipeline_type')
    # ### end Alembic commands ###
